openapi: 3.1.0
info:
  title: Pets API
  version: 1.0.1
  description: An API for managing pets
  x-kubernetes-operator-group: example.com
  x-kubernetes-operator-version: v1
  x-kubernetes-operator-resource-ref: uuid
  x-kubernetes-operator-example-metadata-spec-field-ref: name
  x-kubernetes-operator-include-tags:
    - cats
servers:
  - url: http://localhost:8080
    description: Development server
paths:
  /cats:
    get:
      tags:
        - cats
      operationId: getCats
      summary: Get all cats
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cat'
              examples:
                Cats:
                  $ref: '#/components/examples/Cats'
    post:
      tags:
        - cats
      operationId: createCat
      summary: Create a new cat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cat'
            examples:
              Cat:
                $ref: '#/components/examples/Cat'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
              examples:
                Cat:
                  $ref: '#/components/examples/Cat'
  /cats/{id}:
    get:
      tags:
        - cats
      operationId: getCatById
      summary: Get a cat by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
              examples:
                Cat:
                  $ref: '#/components/examples/Cat'
        '404':
          description: Not found
    put:
      tags:
        - cats
      operationId: updateCatById
      summary: Update a cat by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cat'
            examples:
              Cat:
                $ref: '#/components/examples/Cat'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
              examples:
                Cat:
                  $ref: '#/components/examples/Cat'
        '404':
          description: Not found
    delete:
      tags:
        - cats
      operationId: deleteCatById
      summary: Delete a cat by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
  /dogs:
    get:
      tags:
        - dogs
      operationId: getDogs
      summary: Get all dogs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dog'
              examples:
                Dog:
                  $ref: '#/components/examples/Dogs'
    post:
      tags:
        - dogs
      operationId: createDog
      summary: Create a new dog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dog'
            examples:
              Dog:
                $ref: '#/components/examples/Dog'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dog'
              examples:
                Dog:
                  $ref: '#/components/examples/Dog'
  /dogs/{id}:
    get:
      tags:
        - dogs
      operationId: getDogById
      summary: Get a dog by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dog'
              examples:
                Dogs:
                  $ref: '#/components/examples/Dog'
        '404':
          description: Not found
    put:
      tags:
        - dogs
      operationId: updateDogById
      summary: Update a dog by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dog'
            examples:
              Dog:
                $ref: '#/components/examples/Dog'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dog'
              examples:
                Dog:
                  $ref: '#/components/examples/Dog'
        '404':
          description: Not found
    delete:
      tags:
        - dogs
      operationId: deleteDogById
      summary: Delete a dog by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
  /horses:
    get:
      tags:
        - horses
      operationId: getHorses
      summary: Get all horses
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Horse'
              examples:
                Horses:
                  $ref: '#/components/examples/Horses'
    post:
      tags:
        - horses
      operationId: createHorse
      summary: Create a new horse
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Horse'
            examples:
              Horse:
                $ref: '#/components/examples/Horse'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Horse'
              examples:
                Horse:
                  $ref: '#/components/examples/Horse'
  /horses/{id}:
    get:
      tags:
        - horses
      operationId: getHorseById
      summary: Get a horse by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Horse'
              examples:
                Horse:
                  $ref: '#/components/examples/Horse'
        '404':
          description: Not found
    put:
      tags:
        - horses
      operationId: updateHorseById
      summary: Update a horse by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Horse'
            examples:
              Horse:
                $ref: '#/components/examples/Horse'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Horse'
              examples:
                Horse:
                  $ref: '#/components/examples/Horse'
        '404':
          description: Not found
    delete:
      tags:
        - horses
      operationId: deleteHorseById
      summary: Delete a horse by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
components:
  examples:
    Cat:
      value:
        uuid: 123e4567-e89b-12d3-a456-426614174000
        name: Fluffy
        breed: Persian
        age: 3
    Cats:
      value:
        - uuid: 123e4567-e89b-12d3-a456-426614174000
          name: Fluffy
          breed: Persian
          age: 3
        - uuid: 123e4567-e89b-12d3-a456-426614174001
          name: Whiskers
          breed: Siamese
          age: 2
    Dog:
      value:
        name: Fido
        breed: Bulldog
        age: 3
    Dogs:
      value:
        - uuid: 123e4567-e89b-12d3-a456-426614174000
          name: Fido
          breed: Bulldog
          age: 3
        - uuid: 123e4567-e89b-12d3-a456-426614174001
          name: Rex
          breed: German Shepherd
          age: 5
    Horse:
      value:
        uuid: 123e4567-e89b-12d3-a456-426614174002
        name: Star
        breed: Arabian
        age: 5
    Horses:
      value:
        - uuid: 255b9916-561b-4c8b-9626-53997b01d57d
          name: Star
          breed: Arabian
          age: 5
        - uuid: cf5cf93f-a11f-4b1c-8995-337a54c859c2
          name: Thunder
          breed: Thoroughbred
          age: 7
  schemas:
    Cat:
      type: object
      required:
        - name
        - breed
        - age
      properties:
        uuid:
          type: string
          readOnly: true
          format: uuid
        name:
          type: string
          x-faker: name.findName
        breed:
          type: string
        age:
          type: integer
          x-faker:
            random.number:
              min: 1
              max: 20
    Dog:
      type: object
      required:
        - name
        - breed
        - age
      properties:
        uuid:
          type: string
          readOnly: true
          format: uuid
        name:
          type: string
          x-faker: name.findName
        breed:
          type: string
        age:
          type: integer
          x-faker:
            random.number:
              min: 1
              max: 20
    Horse:
      type: object
      required:
        - name
        - breed
        - age
      properties:
        uuid:
          type: string
          readOnly: true
          format: uuid
        name:
          type: string
          x-faker: name.findName
        breed:
          type: string
        age:
          type: integer
          x-faker:
            random.number:
              min: 1
              max: 20
